BEGIN;
DROP TRIGGER IF EXISTS partner_audit_events_append_only ON partner_audit_events;
DROP TABLE IF EXISTS partner_audit_events;
DROP TRIGGER IF EXISTS partner_tracking_facts_append_only ON partner_tracking_facts;
DROP TRIGGER IF EXISTS partner_job_amendments_append_only ON partner_job_amendments;
DROP FUNCTION IF EXISTS partner_reject_append_only_change();
DROP TABLE IF EXISTS partner_job_amendments;
DROP TABLE IF EXISTS partner_job_settlements;
DROP TABLE IF EXISTS partner_tracking_facts;
DROP TABLE IF EXISTS partner_submission_attempts;
DROP TABLE IF EXISTS partner_site_plan_drawings;
DROP TABLE IF EXISTS partner_outbox_events;
DROP TABLE IF EXISTS partner_jobs;
DROP TABLE IF EXISTS partner_auth_rate_limits;
DROP TABLE IF EXISTS partner_verifications;
DROP TABLE IF EXISTS partner_accounts;
DROP TABLE IF EXISTS partner_sessions;
DROP TABLE IF EXISTS partner_users;
DROP TABLE IF EXISTS partner_companies;
COMMIT;
