BEGIN;
DO $$ BEGIN
  IF EXISTS(SELECT 1 FROM public.partner_job_invoices) OR EXISTS(SELECT 1 FROM public.partner_audit_events WHERE event_type LIKE 'OPS_%') OR EXISTS(SELECT 1 FROM public.partner_users WHERE principal_type='INTERNAL' AND ops_role<>'ADMIN') THEN
    RAISE EXCEPTION 'partner operations rollback refused: 007 records would be lost';
  END IF;
END $$;
DROP TRIGGER IF EXISTS partner_ops_settlement_cancelled_guard ON public.partner_job_settlements;
DROP TRIGGER IF EXISTS partner_ops_settlement_terminal_guard ON public.partner_job_settlements;
DROP TRIGGER IF EXISTS partner_ops_invoice_cancelled_guard ON public.partner_job_invoices;
DROP TRIGGER IF EXISTS partner_ops_invoice_terminal_guard ON public.partner_job_invoices;
DROP TRIGGER IF EXISTS partner_ops_facts_cancelled_guard ON public.partner_tracking_facts;
DROP TRIGGER IF EXISTS partner_ops_audit_guard ON public.partner_audit_events;
DROP FUNCTION IF EXISTS public.partner_ops_job_detail(text,uuid);
DROP FUNCTION IF EXISTS public.partner_ops_partner_user_list(text,uuid);
DROP FUNCTION IF EXISTS public.partner_ops_company_update_full(text,uuid,integer,text,text,text,jsonb);
DROP FUNCTION IF EXISTS public.partner_ops_company_create_full(text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS public.partner_partner_tracking_projection(text,uuid,uuid);
DROP FUNCTION IF EXISTS public.partner_ops_company_list(text);
DROP FUNCTION IF EXISTS public.partner_ops_dashboard(text);
DROP FUNCTION IF EXISTS public.partner_ops_settlement_upsert(text,uuid,uuid,integer,bigint,bigint,text,timestamptz);
DROP FUNCTION IF EXISTS public.partner_ops_invoice_upsert(text,uuid,uuid,integer,text,bigint,timestamptz);
DROP FUNCTION IF EXISTS public.partner_ops_amendment_append(text,uuid,uuid,jsonb);
DROP FUNCTION IF EXISTS public.partner_ops_fact_append(text,uuid,uuid,text,timestamptz);
DROP FUNCTION IF EXISTS public.partner_ops_partner_user_disable(text,uuid,text);
DROP FUNCTION IF EXISTS public.partner_ops_partner_user_create(text,uuid,text,text,text,text);
DROP FUNCTION IF EXISTS public.partner_ops_authorize(text,text);
DROP FUNCTION IF EXISTS public.partner_ops_audit_guard();
DROP FUNCTION IF EXISTS public.partner_ops_terminal_settlement_guard();
DROP FUNCTION IF EXISTS public.partner_ops_invoice_terminal_guard();
DROP FUNCTION IF EXISTS public.partner_ops_fact_guard();
DROP FUNCTION IF EXISTS public.partner_ops_guard_cancelled();
DROP FUNCTION IF EXISTS public.partner_ops_cancelled(uuid,uuid);
ALTER TABLE public.partner_job_amendments DROP CONSTRAINT IF EXISTS partner_amendment_v1_patch;
ALTER TABLE public.partner_job_settlements DROP CONSTRAINT IF EXISTS partner_settlement_ops_max_cents;
REVOKE ALL ON public.partner_companies,public.partner_users,public.partner_accounts,public.partner_sessions,public.partner_jobs,public.partner_tracking_facts,public.partner_job_amendments,public.partner_job_invoices,public.partner_job_settlements,public.partner_audit_events FROM partner_ops_owner;
REVOKE CREATE,USAGE ON SCHEMA public FROM partner_ops_runtime,partner_ops_owner;
DROP TABLE public.partner_job_invoices;
ALTER TABLE public.partner_users DROP CONSTRAINT partner_users_ops_role;
ALTER TABLE public.partner_users DROP COLUMN ops_role;
REVOKE UPDATE(name,email,email_verified,image,updated_at) ON public.partner_users FROM partner_portal_runtime;
GRANT UPDATE ON public.partner_users TO partner_portal_runtime;
ALTER TABLE public.partner_audit_events DROP CONSTRAINT partner_audit_event_type;
ALTER TABLE public.partner_audit_events ADD CONSTRAINT partner_audit_event_type CHECK(event_type IN('LOGIN_SUCCEEDED','LOGIN_FAILED','LOGOUT','USER_PROVISIONED','USER_DISABLED','SESSIONS_REVOKED','LEGACY_CREDENTIAL_REPLACED','SUBMISSION_FROZEN','SUBMISSION_CLAIMED','SUBMISSION_PHASE_CHECKPOINTED','SUBMISSION_FINALIZED','SUBMISSION_FAILED_RETRYABLE','SUBMISSION_RECONCILIATION_REQUIRED','SUBMISSION_EXECUTE_DISCARDED','SUBMISSION_NOTIFICATION_CLAIMED','SUBMISSION_NOTIFICATION_RELEASED','SUBMISSION_NOTIFICATION_DELIVERED','SUBMISSION_NOTIFICATION_DEAD'));
DO $$ BEGIN IF session_user <> 'partner_ops_owner' AND pg_has_role(session_user,'partner_ops_owner','MEMBER') THEN EXECUTE format('REVOKE partner_ops_owner FROM %I',session_user); END IF; END $$;
DROP ROLE partner_ops_runtime;
DROP ROLE partner_ops_owner;
COMMIT;
