// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import FollowupComposer from '@/components/FollowupComposer';
import {emptyControls} from './controls';
import type {QueueItem} from './types';
const item:QueueItem={job:{_id:'aaaaaaaaaaaaaaaaaaaaaaaa',stage:'QUOTE',updatedAt:'v',quote:{c_total:10000}},controls:{revision:1,state:emptyControls(),actorName:'',updatedAt:null},eligibility:{state:'review',reason:'Review'},suggestion:null,earliestFirstApproach:null,sendAvailable:true,sendEnabled:true};
const loaded={enabled:true,attempts:[],contact:{name:'Alex',phoneMobile:'0211234567',email:'alex@example.test'},sms:{senders:[{id:'sms',label:'Work phone'}]},email:{senders:[{id:'email',label:'Work email'}]}};
beforeEach(()=>{vi.stubGlobal('localStorage',{getItem:()=> 'token'});HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};vi.stubGlobal('fetch',vi.fn(async()=>Response.json(loaded)));});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
async function compose(done=vi.fn()) {render(<FollowupComposer item={item} readOnly={false} onCancel={()=>{}} onDone={done} onAccessLost={()=>{}}/>);fireEvent.change(await screen.findByLabelText('Offer amount (NZD discount)'),{target:{value:'650'}});fireEvent.click(screen.getByRole('button',{name:'Send offer'}));return done;}
it('requires confirmation then saves discount and review before one send, using fresh revisions',async()=>{
 const done=await compose();expect(fetch).toHaveBeenCalledTimes(1);expect(screen.queryByRole('checkbox')).toBeNull();expect(screen.getByRole('button',{name:'Confirm and send'}).matches(':disabled')).toBe(false);
 vi.mocked(fetch).mockResolvedValueOnce(Response.json({record:{...item.controls,revision:2}})).mockResolvedValueOnce(Response.json({record:{...item.controls,revision:3}})).mockResolvedValueOnce(Response.json({attempt:{status:'sent'}}));
 fireEvent.click(screen.getByRole('button',{name:'Confirm and send'}));fireEvent.click(screen.getByRole('button',{name:'Sending…'}));await waitFor(()=>expect(done).toHaveBeenCalled());const calls=vi.mocked(fetch).mock.calls.slice(1).map(c=>JSON.parse(c[1]!.body as string));expect(calls).toHaveLength(3);expect(calls[0]).toMatchObject({revision:1,command:{action:'discount',amount:'650'}});expect(calls[1]).toMatchObject({revision:2,command:{action:'review',historyConfirmed:true}});expect(calls[2]).toMatchObject({revision:3,action:'send',channel:'sms',body:expect.stringContaining('$650.00')});
});
it('cancelling confirmation makes no writes',async()=>{await compose();fireEvent.click(screen.getByRole('button',{name:'Back'}));expect(screen.queryByRole('dialog')).toBeNull();expect(fetch).toHaveBeenCalledTimes(1);});
it('does not send or leave the quote after a save conflict',async()=>{const done=await compose();vi.mocked(fetch).mockResolvedValueOnce(Response.json({error:'Quote changed. Refresh.'},{status:409}));fireEvent.click(screen.getByRole('button',{name:'Confirm and send'}));await screen.findByRole('alert');expect(fetch).toHaveBeenCalledTimes(2);expect(done).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Send offer'}).matches(':disabled')).toBe(true);});
it('channel and template selection produce the selected message with the current amount',async()=>{render(<FollowupComposer item={item} readOnly={false} onCancel={()=>{}} onDone={()=>{}} onAccessLost={()=>{}}/>);fireEvent.change(await screen.findByLabelText('Offer amount (NZD discount)'),{target:{value:'300'}});fireEvent.change(screen.getByLabelText('Send by'),{target:{value:'email'}});fireEvent.change(screen.getByLabelText('Template'),{target:{value:'2'}});expect((screen.getByLabelText('Message') as HTMLTextAreaElement).value).toContain('earlier insulation offer');expect((screen.getByLabelText('Message') as HTMLTextAreaElement).value).toContain('$300.00');expect(screen.getByLabelText('Subject')).toBeTruthy();});
