// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import FollowupControls from '@/components/FollowupControls';
import FollowupActions from '@/components/FollowupActions';
import {emptyControls} from './controls';
const item={job:{_id:'aaaaaaaaaaaaaaaaaaaaaaaa',stage:'QUOTE',updatedAt:'v',quote:{status:'DECLINED',c_total:10000}},suggestion:null,earliestFirstApproach:null,eligibility:{state:'review' as const,reason:'Check history'},controls:{revision:3,state:emptyControls(),actorName:'',updatedAt:null}};
beforeEach(()=>{vi.stubGlobal('localStorage',{getItem:()=> 'token'});HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};vi.stubGlobal('fetch',vi.fn(async()=>Response.json({record:item.controls})));});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('saves a shared skip date only after modal confirmation',async()=>{
 const done=vi.fn();render(<FollowupActions item={item} readOnly={false} onDone={done} onAccessLost={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Skip for now'}));expect(fetch).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Skip for'),{target:{value:'custom'}});fireEvent.change(screen.getByLabelText('Skip through'),{target:{value:'2027-01-15'}});fireEvent.click(screen.getByRole('button',{name:'Confirm skip'}));await waitFor(()=>expect(done).toHaveBeenCalled());expect(JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string)).toEqual({revision:3,jobVersion:'v',command:{action:'snooze',date:'2027-01-15'}});
});
it('ignore saves its reason and returns to the queue',async()=>{
 const done=vi.fn();render(<FollowupActions item={item} readOnly={false} onDone={done} onAccessLost={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Ignore'}));const reason=screen.getByLabelText('Reason for ignoring') as HTMLTextAreaElement;expect(reason.required).toBe(true);fireEvent.change(reason,{target:{value:'Customer no longer interested'}});fireEvent.click(screen.getByRole('button',{name:'Ignore quote'}));await waitFor(()=>expect(done).toHaveBeenCalled());expect(JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string).command).toEqual({action:'exclude',reason:'Customer no longer interested'});
});
it('does not write when cancelling skip',()=>{render(<FollowupActions item={item} readOnly={false} onDone={()=>{}} onAccessLost={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Skip for now'}));fireEvent.click(screen.getByRole('button',{name:'Cancel'}));expect(fetch).not.toHaveBeenCalled();expect(screen.queryByRole('dialog')).toBeNull();});
it('locks uncertain saves so they cannot be blindly repeated',async()=>{vi.mocked(fetch).mockRejectedValue(Error('Connection lost'));render(<FollowupActions item={item} readOnly={false} onDone={()=>{}} onAccessLost={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Skip for now'}));fireEvent.click(screen.getByRole('button',{name:'Confirm skip'}));await screen.findByRole('alert');expect(screen.getByRole('button',{name:'Confirm skip'}).matches(':disabled')).toBe(true);});
it('restores an ignored quote from history without any removed edit sections',async()=>{const saved=vi.fn();render(<FollowupControls item={{...item,controls:{...item.controls,state:{...emptyControls(),exclusionReason:'Not interested'}}}} onSaved={saved}/>);expect(screen.queryByText('Record an earlier offer')).toBeNull();expect(screen.queryByText('Review the Dead date and prior offers')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Restore follow-ups'}));await waitFor(()=>expect(saved).toHaveBeenCalled());expect(JSON.parse(vi.mocked(fetch).mock.calls[0][1]!.body as string).command).toEqual({action:'restore'});});

it('keeps ignore editable when the reason is blank or validation fails',async()=>{render(<FollowupActions item={item} readOnly={false} onDone={()=>{}} onAccessLost={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Ignore'}));fireEvent.change(screen.getByLabelText('Reason for ignoring'),{target:{value:'   '}});fireEvent.click(screen.getByRole('button',{name:'Ignore quote'}));await screen.findByRole('alert');expect(fetch).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Ignore quote'}).matches(':disabled')).toBe(false);vi.mocked(fetch).mockResolvedValueOnce(Response.json({error:'Correct the reason'},{status:400}));fireEvent.change(screen.getByLabelText('Reason for ignoring'),{target:{value:'Reason'}});fireEvent.click(screen.getByRole('button',{name:'Ignore quote'}));await screen.findByText('Correct the reason');expect(screen.getByRole('button',{name:'Ignore quote'}).matches(':disabled')).toBe(false);});
