// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import FollowupSender from '@/components/FollowupSender';
import {emptyControls} from './controls';
import type {QueueItem} from './types';
const item:QueueItem={job:{_id:'aaaaaaaaaaaaaaaaaaaaaaaa',stage:'QUOTE',updatedAt:'v'},controls:{revision:1,state:{...emptyControls(),draftDiscountCents:50000},actorName:'',updatedAt:null},eligibility:{state:'due',approach:1,reason:'Due'},suggestion:null,earliestFirstApproach:null,sendAvailable:true,sendEnabled:true};
beforeEach(()=>{vi.stubGlobal('localStorage',{getItem:()=> 'token'});vi.stubGlobal('fetch',vi.fn());vi.mocked(fetch).mockResolvedValue(new Response(JSON.stringify({enabled:true,attempts:[],contact:{phoneMobile:'0211234567'},sms:{senders:[{id:'s',label:'Work phone'}]},email:{senders:[]}})));});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('requires explicit review checkbox before send and submits saved discount template',async()=>{render(<FollowupSender item={item} onChanged={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Compose or check follow-up'}));await screen.findByLabelText('Message');expect((screen.getByLabelText('Message') as HTMLTextAreaElement).value).toContain('$500.00');expect(screen.getByRole('button',{name:'Send offer'}).matches(':disabled')).toBe(true);fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByRole('button',{name:'Send offer'}).matches(':disabled')).toBe(false);});
it('unknown response locks composition until saved status is checked',async()=>{render(<FollowupSender item={item} onChanged={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Compose or check follow-up'}));await screen.findByLabelText('Message');fireEvent.click(screen.getByRole('checkbox'));vi.mocked(fetch).mockRejectedValueOnce(Error('lost'));fireEvent.click(screen.getByRole('button',{name:'Send offer'}));await screen.findByRole('alert');expect(screen.queryByRole('button',{name:'Send offer'})).toBeNull();});
it('note retry posts only note action, never a send',async()=>{vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify({enabled:true,attempts:[{id:'a',status:'sent',noteStatus:'pending',discountCents:50000,approach:1,channel:'sms',body:'Discount $500.00',destination:'0211234567'}],contact:{},sms:{senders:[]},email:{senders:[]}})));render(<FollowupSender item={item} onChanged={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Compose or check follow-up'}));fireEvent.click(await screen.findByRole('button',{name:'Retry job note only'}));await waitFor(()=>expect(fetch).toHaveBeenCalledTimes(2));expect(JSON.parse(vi.mocked(fetch).mock.calls[1][1]!.body as string)).toEqual({action:'note',attemptId:'a'});});
it('allows note recovery after a quote leaves Dead without offering another send',async()=>{vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify({enabled:true,attempts:[{id:'a',status:'sent',noteStatus:'pending',discountCents:50000,approach:1,channel:'sms',body:'Discount $500.00'}],contact:{},sms:{senders:[]},email:{senders:[]}})));render(<FollowupSender item={{...item,sendEnabled:false,job:{...item.job,stage:'JOB'},eligibility:{state:'excluded',reason:'No longer Dead'}}} readOnly onChanged={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Compose or check follow-up'}));expect(await screen.findByRole('button',{name:'Retry job note only'})).toBeTruthy();expect(screen.queryByRole('button',{name:'Send offer'})).toBeNull();});
it('loads a shared template but preserves staff edits when checking status again',async()=>{
 const response=()=>Response.json({enabled:true,attempts:[],contact:{phoneMobile:'0211234567',name:'Alex'},templates:[{channel:'sms',approach:1,subject:'',body:'Shared offer for {{name}}: {{discount}}'}],sms:{senders:[{id:'s',label:'Phone'}]},email:{senders:[]}});
 vi.mocked(fetch).mockImplementation(async()=>response());render(<FollowupSender item={item} onChanged={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Compose or check follow-up'}));const message=await screen.findByLabelText('Message');expect((message as HTMLTextAreaElement).value).toBe('Shared offer for Alex: $500.00');fireEvent.change(message,{target:{value:'My edit $500.00'}});fireEvent.click(screen.getByRole('button',{name:'Compose or check follow-up'}));await waitFor(()=>expect(fetch).toHaveBeenCalledTimes(2));expect((screen.getByLabelText('Message') as HTMLTextAreaElement).value).toBe('My edit $500.00');
});
it('positive evidence verification submits evidence only and never sends content again',async()=>{
 vi.mocked(fetch).mockResolvedValueOnce(Response.json({enabled:true,attempts:[{id:'a',status:'unknown',canVerify:true,noteStatus:'pending',discountCents:50000,approach:1,channel:'email',body:'Discount $500.00',destination:'alex@example.test'}],contact:{},sms:{senders:[]},email:{senders:[]}}));
 render(<FollowupSender item={item} onChanged={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Compose or check follow-up'}));fireEvent.click(await screen.findByText('Verify from sent evidence'));fireEvent.change(screen.getByLabelText('Where you verified this send'),{target:{value:'Gmail Sent folder matches recipient, date and exact offer.'}});fireEvent.click(screen.getByLabelText('I found this exact message in the sending account or device as sent.'));fireEvent.click(screen.getByRole('button',{name:'Record verified send'}));await waitFor(()=>expect(fetch).toHaveBeenCalledTimes(2));expect(JSON.parse(vi.mocked(fetch).mock.calls[1][1]!.body as string)).toEqual({action:'verify',attemptId:'a',confirmed:true,evidence:'Gmail Sent folder matches recipient, date and exact offer.'});
});
