// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import FollowupTemplates from '@/app/jobs/follow-ups/templates/page';
import {defaultTemplates} from './templates';
beforeEach(()=>{vi.stubGlobal('localStorage',{getItem:()=> 'token'});vi.stubGlobal('fetch',vi.fn(async()=>Response.json({record:{revision:2,templates:defaultTemplates()},events:[],canManage:true})));});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('loads four editable shared templates and shows a merged preview',async()=>{render(<FollowupTemplates/>);expect(await screen.findByLabelText('First SMS message')).toBeTruthy();expect(screen.getAllByText(/\$500.00/).length).toBeGreaterThan(0);expect(screen.getByRole('button',{name:'Save shared templates'}).matches(':disabled')).toBe(false);});
it('preserves unsaved edits on conflict and requires reload',async()=>{render(<FollowupTemplates/>);const body=await screen.findByLabelText('First SMS message');fireEvent.change(body,{target:{value:'Edited {{discount}}'}});vi.mocked(fetch).mockResolvedValueOnce(Response.json({error:'Templates changed. Reload before saving.'},{status:409}));fireEvent.click(screen.getByRole('button',{name:'Save shared templates'}));await screen.findByRole('alert');expect((body as HTMLTextAreaElement).value).toBe('Edited {{discount}}');expect(screen.getByRole('button',{name:'Save shared templates'}).matches(':disabled')).toBe(true);});
it('read-only staff cannot save shared defaults',async()=>{vi.mocked(fetch).mockResolvedValueOnce(Response.json({record:{revision:0,templates:defaultTemplates()},events:[],canManage:false}));render(<FollowupTemplates/>);await screen.findByLabelText('First SMS message');expect(screen.getByRole('button',{name:'Save shared templates'}).matches(':disabled')).toBe(true);});
it('allows correction of a rejected template without losing the draft',async()=>{render(<FollowupTemplates/>);const body=await screen.findByLabelText('First SMS message');fireEvent.change(body,{target:{value:'Missing amount'}});vi.mocked(fetch).mockResolvedValueOnce(Response.json({error:'Include {{discount}}'},{status:400}));fireEvent.click(screen.getByRole('button',{name:'Save shared templates'}));await screen.findByRole('alert');expect((body as HTMLTextAreaElement).value).toBe('Missing amount');expect(screen.getByRole('button',{name:'Save shared templates'}).matches(':disabled')).toBe(false);});
