"use client";
import Link from "next/link";
import { useCallback,useEffect,useRef,useState } from "react";
type NotificationState="PENDING"|"DELIVERED"|"DEAD";
type Status={state:string;checkpoint:string;errorCode:string|null;updatedAt:string|null;completedAt:string|null;notification?:NotificationState};
const SUBMISSION_TERMINAL=new Set(["SUCCEEDED","RECONCILIATION_REQUIRED"]);const terminal=(status:Status)=>SUBMISSION_TERMINAL.has(status.state)&&(!status.notification||status.notification==="DELIVERED"||status.notification==="DEAD");
function copy(state:string,demoMode:boolean){if(state==="SUCCEEDED")return{title:"Submitted",body:demoMode?"The fictional legacy submission completed. This result is independent of the internal demo notification below.":"The submission completed. The saved quote and plans remain read-only.",tone:"bg-emerald-50 text-emerald-900 border-emerald-200"};if(state==="FAILED_RETRYABLE"||state==="RECONCILIATION_REQUIRED")return{title:"Contact Insulmax",body:"This submission needs a check. Please contact the Insulmax team directly and give them your job reference. You do not need to submit it again.",tone:"bg-amber-50 text-amber-900 border-amber-200"};return{title:state==="PROCESSING"?"Submission processing":"Submission received",body:demoMode?"The saved quote and plans are read-only while the fictional worker verifies and transfers them.":"The saved quote and plans are read-only while the submission is processed.",tone:"bg-blue-50 text-blue-950 border-blue-200"};}
export default function PartnerSubmissionStatusPanel({jobId,initialStatus,demoMode=false,backgroundOnly=false}:{jobId:string;initialStatus:Status;demoMode?:boolean;backgroundOnly?:boolean}){
 const[status,setStatus]=useState(initialStatus),[notice,setNotice]=useState(""),[authAction,setAuthAction]=useState(false),[working,setWorking]=useState(false);const inFlight=useRef(false),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const accept=useCallback((next:Status)=>{if(mounted.current){setStatus(next);setNotice("");}},[]);
 const resume=useCallback(async()=>{if(inFlight.current||terminal(status))return;inFlight.current=true;if(mounted.current)setWorking(true);try{const response=await fetch(`/api/partner/jobs/${jobId}/submission/resume`,{method:"POST",cache:"no-store"});const data=await response.json() as{status?:Status};if(response.ok&&data.status)accept(data.status);else if(mounted.current){setNotice(response.status===401?"Your session expired. Sign in again to continue.":"Recovery could not be confirmed. The last verified status remains shown; try again shortly.");if(response.status===401)setAuthAction(true);}}catch{if(mounted.current)setNotice("Recovery could not be confirmed. The last verified status remains shown; try again shortly.");}finally{inFlight.current=false;if(mounted.current)setWorking(false);}},[accept,jobId,status]);
 useEffect(()=>{if(demoMode&&!terminal(status))void resume();},[demoMode,resume,status]);
 useEffect(()=>{if(terminal(status))return;let cancelled=false,timer:number|undefined,attempt=0,controller:AbortController|null=null;const poll=async()=>{let retryAfterMs=0;if(cancelled)return;if(document.visibilityState==="hidden"){timer=window.setTimeout(poll,8_000);return;}controller=new AbortController();const timeout=window.setTimeout(()=>controller?.abort(),8_000);try{const response=await fetch(`/api/partner/jobs/${jobId}/submission`,{cache:"no-store",signal:controller.signal});if([401,403,404].includes(response.status)){cancelled=true;setAuthAction(response.status!==404);setNotice(response.status===401?"Your session expired. Sign in again to continue.":response.status===403?"Status access is unavailable. Sign in again before reloading.":"This job is no longer available.");return;}if(response.ok){const data=await response.json() as{status?:Status};if(data.status){accept(data.status);if(terminal(data.status))return;}}else{if(response.status===429){const seconds=Number(response.headers.get("retry-after"));retryAfterMs=Number.isInteger(seconds)&&seconds>0?Math.min(60,seconds)*1_000:15_000;}setNotice(response.status===429?"Status checks are temporarily limited. This page will try again.":"Status could not be refreshed. The last verified state remains visible.");}}catch{if(!cancelled)setNotice("Status could not be refreshed. The last verified state remains visible.");}finally{window.clearTimeout(timeout);}if(!cancelled){attempt+=1;timer=window.setTimeout(poll,Math.max(retryAfterMs,Math.min(15_000,2_000*2**Math.min(attempt,3))));}};timer=window.setTimeout(poll,2_000);return()=>{cancelled=true;if(timer)window.clearTimeout(timer);controller?.abort();};},[accept,jobId,status]);
 if(backgroundOnly)return null;
 const text=copy(status.state,demoMode),notification=status.notification;return <section className={`rounded-2xl border p-5 ${text.tone}`} aria-live="polite" aria-atomic="true"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-bold">{text.title}</h2><span className="rounded-full bg-white/70 px-2.5 py-1 text-xs font-bold uppercase tracking-wide">{["FAILED_RETRYABLE","RECONCILIATION_REQUIRED"].includes(status.state)?"Contact Insulmax":status.state.replaceAll("_"," ")}</span></div><p className="mt-2 text-sm leading-6">{text.body}</p>{notification?<div className="mt-4 rounded-xl border border-current/15 bg-white/65 p-3"><p className="text-xs font-bold uppercase tracking-wide">Fictional internal notification</p><p className="mt-1 text-sm font-semibold">{notification==="PENDING"?"Pending":notification==="DELIVERED"?"Delivered in the demo only":"Stopped without delivery"}</p></div>:null}{notice?<p role="status" className="mt-3 text-sm font-semibold">{notice}</p>:null}<div className="mt-4 flex flex-wrap gap-3">{demoMode&&!terminal(status)?<button type="button" onClick={()=>void resume()} disabled={working} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#1a3a4a] px-4 text-sm font-bold text-white disabled:cursor-wait disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#e85d04]">{working?"Checking…":"Refresh and resume"}</button>:null}{authAction?<Link href="/partner/login?reason=session-expired" className="inline-flex min-h-11 items-center rounded-xl border border-current px-4 font-semibold underline">Sign in again</Link>:null}</div></section>;
}
