import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { createHash,randomUUID } from "node:crypto";
import { EMPTY_SITE_PLAN_DOCUMENT } from "../site-plan-drawings";
import { getPartnerDemoPool, partnerDemoSubmissionPoisoned } from "./demo";
import type { PartnerSql } from "./db";
import { partnerDemoWorkerState,resetPartnerDemoSubmissionRuntime,signalPartnerDemoSubmissionWorker } from "./demo-submission-worker";
import { processFictionalLegacyProjection } from "./legacy/factory";
import { processFictionalNotificationProjection } from "./legacy/notification";
import { readBoundLegacyCredential,type BoundLegacyCredential } from "./legacy/claimed-credential";
import { createFictionalLegacyAdapterTestHarness,FictionalLegacyWorld,type FictionalLegacyAdapterController } from "./legacy/fake";
import { PartnerSubmissionRepository } from "./submission-repository";
import { PartnerSubmissionService } from "./submission-service";
import { createPartnerDemoSubmissionWorkerRepository } from "./demo-submission-worker-repository";
import { PartnerSubmissionWorkerEngine } from "./submission-worker-engine";
import { createFictionalNotificationAdapterTestHarness } from "./legacy/notification";
import { PartnerSitePlanRepository } from "./site-plan-repository";
import { renderPartnerSitePlanPdf } from "./site-plan-renderer";
import { canonicalJson } from "./site-plan-hash";

const companyId="11111111-1111-4111-8111-111111111111",jobId="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5";
const scope={companyId,jobId};
const principal={userId:"demo-partner-northwind",companyId,principalType:"PARTNER" as const};
const env=()=>({...process.env});
async function acceptedFixture(){const pool=getPartnerDemoPool(),repository=new PartnerSubmissionRepository(pool,env()),service=new PartnerSubmissionService(repository,{env:env()}),preflight=await repository.preflight(principal,jobId);expect(preflight).not.toBeNull();expect((await service.submit(principal,jobId,{jobRevision:preflight!.jobRevision,floorPlanRevision:2,idempotencyKey:crypto.randomUUID()},"127.0.0.1")).outcome).toBe("accepted");const request=await pool.query<{id:string}>("SELECT id FROM partner_submission_requests WHERE company_id=$1 AND job_id=$2",[companyId,jobId]);return{pool,repository,service,requestId:request.rows[0].id,workerScope:{...scope,requestId:request.rows[0].id}};}
function fictionalResolver(configure?:(adapter:FictionalLegacyAdapterController)=>void){const world=new FictionalLegacyWorld();let adapter:FictionalLegacyAdapterController|null=null;return{resolve:(binding:BoundLegacyCredential)=>{const value=readBoundLegacyCredential(binding);if(!value)throw new Error("fictional binding missing");if(!adapter){adapter=createFictionalLegacyAdapterTestHarness(value.identity,world);if(!adapter)throw new Error("fictional adapter missing");configure?.(adapter);}return{kind:"AVAILABLE" as const,adapter};},adapter:()=>adapter};}
async function corruptClaimProjection(change:(text:string,row:Record<string,unknown>)=>void){const{pool,workerScope}=await acceptedFixture();const sql={query:async(text:string,values?:readonly unknown[])=>{const result=await pool.query(text,[...(values??[])]);if(result.rows[0])change(text,result.rows[0] as Record<string,unknown>);return result;}} as PartnerSql;const resolveAdapter=vi.fn();const result=await new PartnerSubmissionWorkerEngine(createPartnerDemoSubmissionWorkerRepository(sql,workerScope,env()),{env:env(),leaseSeconds:120,deadlineMs:45_000,resolveAdapter}).runOnce("corrupt-claim");expect(result.submission).toBe("RECONCILED");expect(resolveAdapter).not.toHaveBeenCalled();expect(processFictionalLegacyProjection()).toMatchObject({jobs:0,adapters:[]});}
function repinSnapshot(row:Record<string,unknown>,change:(value:Record<string,unknown>)=>void){const value=structuredClone(row.snapshot_data) as Record<string,unknown>;change(value);const canonical=canonicalJson(value),job=value.job as Record<string,unknown>,snapshotSha256=createHash("sha256").update(canonical).digest("hex");row.canonical_document=canonical;row.snapshot_data=value;row.snapshot_sha256=snapshotSha256;row.snapshot_byte_size=Buffer.byteLength(canonical);row.request_hash=createHash("sha256").update(canonicalJson({schemaVersion:1,snapshotSha256,jobRevision:job.revision,floorPlanRevision:job.floorPlanRevision})).digest("hex");}
async function malformedStoredGraph(change:(pool:ReturnType<typeof getPartnerDemoPool>)=>Promise<void>){const{pool,workerScope}=await acceptedFixture();await change(pool);const resolveAdapter=vi.fn();const result=await new PartnerSubmissionWorkerEngine(createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env()),{env:env(),leaseSeconds:120,deadlineMs:45_000,resolveAdapter}).runOnce("malformed-identity");expect(result.submission).toBe("RECONCILED");expect(resolveAdapter).not.toHaveBeenCalled();expect(processFictionalLegacyProjection()).toMatchObject({jobs:0,adapters:[]});}
beforeEach(()=>{vi.stubEnv("NODE_ENV","test");vi.stubEnv("PARTNER_DEMO_MODE","true");vi.stubEnv("PARTNER_DEMO_CONFIRM","LOCAL_FICTIONAL_DATA_ONLY");vi.stubEnv("PARTNER_APP_ORIGIN","http://127.0.0.1:3000/");});
afterEach(async()=>{await resetPartnerDemoSubmissionRuntime(env()).catch(()=>undefined);vi.unstubAllEnvs();});

describe("fictional E5 submission worker",()=>{
  it("submits after renaming an existing floor and updating its PDF",async()=>{
    vi.stubEnv("NODE_ENV","development");
    const pool=getPartnerDemoPool(),plans=new PartnerSitePlanRepository(pool as never);
    const floor=(await plans.list(principal,jobId))!.floors[0];
    expect((await plans.patch(principal,jobId,floor.id,floor.revision,{name:"Ground floor — review",document:floor.document})).outcome).toBe("updated");
    const render=await plans.renderSnapshot(principal,jobId,floor.id);expect(render).not.toBeNull();
    const pdf=await renderPartnerSitePlanPdf(render!.input);
    expect((await plans.publish(principal,jobId,floor.id,render!,pdf,"Ground floor — review.pdf"))?.pdfReady).toBe(true);
    const repository=new PartnerSubmissionRepository(pool,env()),service=new PartnerSubmissionService(repository,{env:env()});
    const preflight=await repository.preflight(principal,jobId);
    expect((await service.submit(principal,jobId,{jobRevision:preflight!.jobRevision,floorPlanRevision:preflight!.floorPlanRevision,idempotencyKey:randomUUID()},"127.0.0.1")).outcome).toBe("accepted");
    await signalPartnerDemoSubmissionWorker(scope,env());
    expect(await service.status(principal,jobId)).toMatchObject({state:"SUCCEEDED",checkpoint:"FINALIZED",notification:"DELIVERED"});
  },30_000);
  it("drains ten concurrent signals through one real engine and exactly one fictional effect set",async()=>{
    vi.stubGlobal("fetch",vi.fn(()=>{throw new Error("network must not be called");}));
    const pool=getPartnerDemoPool(),service=new PartnerSubmissionService(new PartnerSubmissionRepository(pool,env()),{env:env()});const preflight=await new PartnerSubmissionRepository(pool,env()).preflight(principal,jobId);expect(preflight).toMatchObject({state:"DRAFT",floorPlanRevision:2});
    const accepted=await service.submit(principal,jobId,{jobRevision:preflight!.jobRevision,floorPlanRevision:2,idempotencyKey:"12345678-1234-4123-8123-123456789abc"},"127.0.0.1");expect(accepted.outcome).toBe("accepted");
    const results=await Promise.all(Array.from({length:10},()=>signalPartnerDemoSubmissionWorker(scope,env())));expect(results.every(result=>result.state==="IDLE")).toBe(true);expect(partnerDemoWorkerState()).toMatchObject({state:"IDLE",signals:10,poisoned:false});
    const status=await service.status(principal,jobId);expect(status).toMatchObject({state:"SUCCEEDED",checkpoint:"FINALIZED",notification:"DELIVERED"});
    const requests=await pool.query("SELECT id FROM partner_submission_requests WHERE company_id=$1 AND job_id=$2",[companyId,jobId]),deliveries=await pool.query("SELECT ordinal FROM partner_submission_plan_deliveries WHERE company_id=$1 AND job_id=$2",[companyId,jobId]),notificationsRows=await pool.query("SELECT id FROM partner_outbox_events WHERE company_id=$1 AND job_id=$2 AND topic='PARTNER_SUBMISSION_COMPLETED'",[companyId,jobId]);expect([requests.rowCount,deliveries.rowCount,notificationsRows.rowCount]).toEqual([1,2,1]);
    const remote=processFictionalLegacyProjection();expect(remote.jobs).toBe(1);expect(remote.adapters).toHaveLength(1);expect(remote.adapters[0].callCounts).toEqual({createLead:1,findLead:1,getJob:3,updateQuote:1,readQuote:1,uploadPlan:2,attachPlans:1,readAttachedPlans:4});
    const notifications=processFictionalNotificationProjection();expect(notifications).toMatchObject({deliverCalls:1,lookupCalls:0});expect(notifications.enqueues).toHaveLength(1);expect(notifications.deliveries).toHaveLength(1);
  });
  it("keeps a successful submission successful when the independent fictional notification dies",async()=>{const pool=getPartnerDemoPool(),repository=new PartnerSubmissionRepository(pool,env()),service=new PartnerSubmissionService(repository,{env:env()}),preflight=await repository.preflight(principal,jobId);expect((await service.submit(principal,jobId,{jobRevision:preflight!.jobRevision,floorPlanRevision:2,idempotencyKey:"87654321-4321-4321-8321-cba987654321"},"127.0.0.1")).outcome).toBe("accepted");const request=await pool.query<{id:string}>("SELECT id FROM partner_submission_requests WHERE company_id=$1 AND job_id=$2",[companyId,jobId]);const notification=createFictionalNotificationAdapterTestHarness(["PERMANENT"]);expect(notification).not.toBeNull();const engine=new PartnerSubmissionWorkerEngine(createPartnerDemoSubmissionWorkerRepository(pool,{...scope,requestId:request.rows[0].id},env()),{env:env(),leaseSeconds:120,deadlineMs:45_000,resolveNotificationAdapter:()=>notification});const result=await engine.runOnce("fictional-dead-notification");expect(result).toEqual({submission:"SUCCEEDED",notification:"DEAD"});expect(await service.status(principal,jobId)).toMatchObject({state:"SUCCEEDED",checkpoint:"FINALIZED",notification:"DEAD"});expect(notification!.deliveries).toHaveLength(0);expect(notification!.enqueues).toHaveLength(0);});
  it("reset atomically restores the seeded ready draft and clears remote worlds",async()=>{getPartnerDemoPool();await resetPartnerDemoSubmissionRuntime(env());const pool=getPartnerDemoPool();const job=await pool.query<{submission_state:string;floor_plan_revision:number|string}>("SELECT submission_state,floor_plan_revision FROM partner_jobs WHERE id=$1",[jobId]);expect(job.rows[0]).toEqual({submission_state:"DRAFT",floor_plan_revision:2});expect(processFictionalLegacyProjection()).toMatchObject({adapters:[],jobs:0});expect(processFictionalNotificationProjection()).toEqual({deliverCalls:0,lookupCalls:0,enqueues:[],deliveries:[]});});
  it("hard-disables production and non-loopback execution before pool or provider selection",async()=>{const unsafe={...env(),NODE_ENV:"production" as const,PARTNER_APP_ORIGIN:"https://example.com/"} as NodeJS.ProcessEnv;expect(()=>signalPartnerDemoSubmissionWorker(scope,unsafe)).toThrow("PARTNER_DEMO_WORKER_FORBIDDEN");expect(partnerDemoWorkerState().signals).toBe(0);});
  it("does not let another tenant's signal claim, count, or alter the authorized job",async()=>{const{service}=await acceptedFixture();const harbour={companyId:"22222222-2222-4222-8222-222222222222",jobId};await signalPartnerDemoSubmissionWorker(harbour,env());expect(await service.status(principal,jobId)).toMatchObject({state:"QUEUED",checkpoint:"FROZEN"});expect(processFictionalLegacyProjection()).toMatchObject({jobs:0,adapters:[]});expect(processFictionalNotificationProjection()).toEqual({deliverCalls:0,lookupCalls:0,enqueues:[],deliveries:[]});await signalPartnerDemoSubmissionWorker(scope,env());expect(await service.status(principal,jobId)).toMatchObject({state:"SUCCEEDED",notification:"DELIVERED"});});
  it("submits a newly created drawing rendered through the normal placeholder-backed demo PDF path",async()=>{vi.stubEnv("NODE_ENV","development");const pool=getPartnerDemoPool(),generatedJobId=randomUUID();await pool.query(`INSERT INTO partner_jobs(id,company_id,created_by_user_id,client_reference,billing_model_snapshot,customer_name,customer_mobile,customer_email,site_address,lead_sources,notes,quote_data,quote_initialized_at,quote_defaults_revision,quote_defaults_snapshot,quote_total_cents) SELECT $1,company_id,created_by_user_id,'NW-E5-GENERATED',billing_model_snapshot,customer_name,customer_mobile,customer_email,site_address,lead_sources,'Generated through the normal E5 path',quote_data,quote_initialized_at,quote_defaults_revision,quote_defaults_snapshot,quote_total_cents FROM partner_jobs WHERE company_id=$2 AND id=$3`,[generatedJobId,companyId,jobId]);const plans=new PartnerSitePlanRepository(pool as never),document={...EMPTY_SITE_PLAN_DOCUMENT,walls:[{id:"generated-wall",start:{x:1,y:1},end:{x:7,y:1},style:"solid" as const}]};const created=await plans.create(principal,generatedJobId,0,"Generated ground",document);if(created.outcome!=="updated")throw new Error("generated drawing failed");const drawingId=created.collection.floors[0].id,snapshot=await plans.renderSnapshot(principal,generatedJobId,drawingId);if(!snapshot)throw new Error("generated snapshot missing");const pdf=await renderPartnerSitePlanPdf(snapshot.input),published=await plans.publish(principal,generatedJobId,drawingId,snapshot,pdf,"Generated ground.pdf");expect(published?.pdfReady).toBe(true);const artifact=(await pool.query<{id:string;pdf_bytes:Buffer;byte_size:number|string;content_sha256:string}>("SELECT id,pdf_bytes,byte_size,content_sha256 FROM partner_site_plan_pdf_artifacts WHERE company_id=$1 AND job_id=$2 AND drawing_id=$3",[companyId,generatedJobId,drawingId])).rows[0];expect(Buffer.from(artifact.pdf_bytes).toString()).toBe("%PDF-1.7 local-demo-placeholder");expect(Number(artifact.byte_size)).toBe(Buffer.byteLength("%PDF-1.7 local-demo-placeholder"));expect(artifact.content_sha256).toBe(pdf.contentSha256);const repository=new PartnerSubmissionRepository(pool,env()),service=new PartnerSubmissionService(repository,{env:env()}),preflight=await repository.preflight(principal,generatedJobId);expect(preflight).toMatchObject({state:"DRAFT",floorPlanRevision:1});expect((await service.submit(principal,generatedJobId,{jobRevision:preflight!.jobRevision,floorPlanRevision:1,idempotencyKey:randomUUID()},"127.0.0.1")).outcome).toBe("accepted");await signalPartnerDemoSubmissionWorker({companyId,jobId:generatedJobId},env());expect(await service.status(principal,generatedJobId)).toMatchObject({state:"SUCCEEDED",checkpoint:"FINALIZED",notification:"DELIVERED"});},30_000);
  it("reclaims an expired lease while fencing the stale worker",async()=>{const{pool,workerScope}=await acceptedFixture();const store=createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env()),first=await store.claimSubmission("first",120);expect(first?.kind).toBe("LEASE");if(!first||first.kind!=="LEASE")throw new Error("lease missing");await pool.query("UPDATE partner_outbox_events SET lease_expires_at=now()-interval '1 second' WHERE request_id=$1",[workerScope.requestId]);expect(await store.heartbeatSubmission(first.lease,120)).toBe(false);expect(await store.releaseSubmission(first.lease,"PROVIDER_TIMEOUT",1)).toBe("DENIED");const second=await store.claimSubmission("second",120);expect(second?.kind).toBe("LEASE");if(!second||second.kind!=="LEASE")throw new Error("replacement lease missing");expect(second.lease.fenceToken).toBeGreaterThan(first.lease.fenceToken);expect(await store.checkpoint(first.lease,"CREATE_STARTED")).toBe(false);expect(await store.heartbeatSubmission(second.lease,120)).toBe(true);});
  it("reclaims expired notification work with a new attempt and denies the old fence",async()=>{const{pool,workerScope}=await acceptedFixture(),initialStore=createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env());const engine=new PartnerSubmissionWorkerEngine(initialStore,{env:env(),leaseSeconds:120,deadlineMs:45_000,resolveNotificationAdapter:()=>null});expect((await engine.runOnce("notification-seed")).submission).toBe("SUCCEEDED");const store=createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env()),first=await store.claimNotification("notification-first",120);expect(first?.kind).toBe("LEASE");if(!first||first.kind!=="LEASE")throw new Error("notification lease missing");await pool.query("UPDATE partner_outbox_events SET lease_expires_at=now()-interval '1 second' WHERE id=$1",[first.lease.eventId]);expect(await store.heartbeatNotification(first.lease,120)).toBe(false);expect(await store.checkpointNotificationAccepted(first.lease,"stale-receipt")).toBe(false);expect(await store.releaseNotification(first.lease,"PROVIDER_TIMEOUT",1)).toBe("DENIED");const second=await store.claimNotification("notification-second",120);expect(second?.kind).toBe("LEASE");if(!second||second.kind!=="LEASE")throw new Error("replacement notification lease missing");expect(second.lease.attemptNumber).toBe(first.lease.attemptNumber+1);expect(second.lease.fenceToken).toBeGreaterThan(first.lease.fenceToken);expect(await store.finalizeNotification(first.lease,"stale-receipt")).toBe(false);expect(await store.heartbeatNotification(second.lease,120)).toBe(true);});
  it("reconciles a zero-plan frozen request without selecting a provider",async()=>{const{pool,workerScope}=await acceptedFixture();await pool.query("DELETE FROM partner_submission_plan_deliveries WHERE company_id=$1 AND job_id=$2 AND request_id=$3",[companyId,jobId,workerScope.requestId]);await pool.query("DELETE FROM partner_submission_plan_manifest WHERE company_id=$1 AND job_id=$2",[companyId,jobId]);const claim=await createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env()).claimSubmission("malformed",120);expect(claim?.kind).toBe("RECONCILED");expect(processFictionalLegacyProjection()).toMatchObject({jobs:0,adapters:[]});expect((await pool.query("SELECT submission_state FROM partner_jobs WHERE id=$1",[jobId])).rows[0].submission_state).toBe("RECONCILIATION_REQUIRED");});
  it("reconciles an incompatible job/checkpoint graph before selecting a provider",async()=>{const{pool,workerScope}=await acceptedFixture();await pool.query("UPDATE partner_jobs SET submission_checkpoint='QUOTE_UPDATED' WHERE company_id=$1 AND id=$2",[companyId,jobId]);const claim=await createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env()).claimSubmission("bad-graph",120);expect(claim?.kind).toBe("RECONCILED");expect(processFictionalLegacyProjection()).toMatchObject({jobs:0,adapters:[]});});
  it("reconciles corrupt manifest-to-artifact provenance before selecting a provider",async()=>{const{pool,workerScope}=await acceptedFixture();await pool.query("UPDATE partner_site_plan_pdf_artifacts SET render_hash=$1 WHERE company_id=$2 AND job_id=$3 AND id=(SELECT artifact_id FROM partner_submission_plan_manifest WHERE company_id=$2 AND job_id=$3 ORDER BY ordinal LIMIT 1)",["b".repeat(64),companyId,jobId]);const claim=await createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env()).claimSubmission("bad-provenance",120);expect(claim?.kind).toBe("RECONCILED");expect(processFictionalLegacyProjection()).toMatchObject({jobs:0,adapters:[]});expect((await pool.query("SELECT submission_state FROM partner_jobs WHERE company_id=$1 AND id=$2",[companyId,jobId])).rows[0].submission_state).toBe("RECONCILIATION_REQUIRED");});
  it("reconciles corrupt canonical snapshot text before adapter resolution",async()=>{await corruptClaimProjection((text,row)=>{if(text.includes("SELECT o.id,o.company_id"))row.canonical_document='{"broken":';});});
  it("reconciles a corrupt snapshot hash before adapter resolution",async()=>{await corruptClaimProjection((text,row)=>{if(text.includes("SELECT o.id,o.company_id"))row.snapshot_sha256="0".repeat(64);});});
  it("reconciles a nondeterministic remote filename before adapter resolution",async()=>{await corruptClaimProjection((text,row)=>{if(text.includes("SELECT m.*,d.drawing_id delivery_drawing_id"))row.remote_file_name="foreign.pdf";});});
  it("reconciles unexpected snapshot job keys before adapter resolution",async()=>{await corruptClaimProjection((text,row)=>{if(text.includes("SELECT o.id,o.company_id"))repinSnapshot(row,value=>{(value.job as Record<string,unknown>).unexpected="forbidden";});});});
  it("reconciles malformed lead and quote shapes before adapter resolution",async()=>{await corruptClaimProjection((text,row)=>{if(text.includes("SELECT o.id,o.company_id"))repinSnapshot(row,value=>{const job=value.job as Record<string,unknown>;job.customer={name:12,mobile:null,email:[]};job.quote={};});});});
  it("reconciles malformed plan documents before adapter resolution",async()=>{await corruptClaimProjection((text,row)=>{if(text.includes("SELECT o.id,o.company_id"))repinSnapshot(row,value=>{((value.plans as Array<Record<string,unknown>>)[0]).document={};});});});
  it("reconciles a repinned but foreign plan render hash before adapter resolution",async()=>{await corruptClaimProjection((text,row)=>{if(text.includes("SELECT o.id,o.company_id"))repinSnapshot(row,value=>{const plan=(value.plans as Array<Record<string,unknown>>)[0],artifact=plan.artifact as Record<string,unknown>;artifact.renderHash="d".repeat(64);});});});
  it("rejects legacy identity on FROZEN before adapter resolution",async()=>{await malformedStoredGraph(async pool=>{await pool.query("UPDATE partner_jobs SET legacy_job_id='foreign',legacy_job_number=99 WHERE company_id=$1 AND id=$2",[companyId,jobId]);});});
  it("requires legacy identity at LEAD_CREATED before adapter resolution",async()=>{await malformedStoredGraph(async pool=>{await pool.query("UPDATE partner_jobs SET submission_state='UPDATING_QUOTE',submission_checkpoint='LEAD_CREATED',submission_started_at=now() WHERE company_id=$1 AND id=$2",[companyId,jobId]);});});
  it("requires final quote identity and verified fingerprint at QUOTE_UPDATED before adapter resolution",async()=>{await malformedStoredGraph(async pool=>{await pool.query("UPDATE partner_jobs SET submission_state='ATTACHING_PLANS',submission_checkpoint='QUOTE_UPDATED',submission_started_at=now(),legacy_job_id='foreign',legacy_job_number=99,final_quote_number='WRONG' WHERE company_id=$1 AND id=$2",[companyId,jobId]);});});
  it("normalizes a QUOTE_UPDATED retry and eventually finalizes without repeating lead or quote effects",async()=>{const{pool,workerScope}=await acceptedFixture(),store=createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env()),resolver=fictionalResolver(adapter=>adapter.queue("uploadPlan","DEFINITE_NO_EFFECT"));const first=await new PartnerSubmissionWorkerEngine(store,{env:env(),leaseSeconds:120,deadlineMs:45_000,resolveAdapter:resolver.resolve}).runOnce("quote-retry-1");expect(first.submission).toBe("RELEASED");expect((await pool.query("SELECT submission_state,submission_checkpoint FROM partner_jobs WHERE id=$1",[jobId])).rows[0]).toEqual({submission_state:"FAILED_RETRYABLE",submission_checkpoint:"QUOTE_UPDATED"});const second=await new PartnerSubmissionWorkerEngine(store,{env:env(),leaseSeconds:120,deadlineMs:45_000,resolveAdapter:resolver.resolve}).runOnce("quote-retry-2");expect(second.submission).toBe("SUCCEEDED");expect(resolver.adapter()?.callCounts).toMatchObject({createLead:1,updateQuote:1});expect((await pool.query("SELECT submission_state,submission_checkpoint FROM partner_jobs WHERE id=$1",[jobId])).rows[0]).toEqual({submission_state:"SUBMITTED",submission_checkpoint:"FINALIZED"});});
  it("normalizes a PLANS_ATTACHED retry and finalizes without repeating remote mutations",async()=>{const{pool,workerScope}=await acceptedFixture(),store=createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env()),resolver=fictionalResolver(),originalFinalize=store.finalizeSubmission.bind(store);let released=false;store.finalizeSubmission=async(lease,count)=>{if(!released){released=true;expect(await store.releaseSubmission(lease,"PROVIDER_TIMEOUT",1)).toBe("RELEASED");return false;}return originalFinalize(lease,count);};const first=await new PartnerSubmissionWorkerEngine(store,{env:env(),leaseSeconds:120,deadlineMs:45_000,resolveAdapter:resolver.resolve}).runOnce("attached-retry-1");expect(first.submission).toBe("LEASE_LOST");expect((await pool.query("SELECT submission_state,submission_checkpoint FROM partner_jobs WHERE id=$1",[jobId])).rows[0]).toEqual({submission_state:"FAILED_RETRYABLE",submission_checkpoint:"PLANS_ATTACHED"});const counts={...resolver.adapter()!.callCounts};store.finalizeSubmission=originalFinalize;const second=await new PartnerSubmissionWorkerEngine(store,{env:env(),leaseSeconds:120,deadlineMs:45_000,resolveAdapter:resolver.resolve}).runOnce("attached-retry-2");expect(second.submission).toBe("SUCCEEDED");expect(resolver.adapter()?.callCounts.createLead).toBe(counts.createLead);expect(resolver.adapter()?.callCounts.updateQuote).toBe(counts.updateQuote);expect(resolver.adapter()?.callCounts.uploadPlan).toBe(counts.uploadPlan);expect(resolver.adapter()?.callCounts.attachPlans).toBe(counts.attachPlans);});
  it("denies finalize when identity, drawing snapshot, artifact provenance, or an exact pointer drifts",async()=>{const{pool,workerScope}=await acceptedFixture(),store=createPartnerDemoSubmissionWorkerRepository(pool,workerScope,env()),claim=await store.claimSubmission("finalize-hostile",120);if(!claim||claim.kind!=="LEASE")throw new Error("lease missing");const lease=claim.lease;expect(await store.checkpoint(lease,"CREATE_STARTED")).toBe(true);expect(await store.checkpoint(lease,"LEAD_CREATED",{legacyId:"fictional-job-1",legacyNumber:1})).toBe(true);expect(await store.checkpointQuoteVerified(lease,"a".repeat(64))).toBe(true);const plans=await store.claimedPlans(lease);for(const plan of plans){const key=`fictional/${plan.ordinal}`;expect(await store.beginUpload(lease,plan.ordinal)).toBe("STARTED");expect(await store.checkpoint(lease,"PLAN_UPLOADED",{ordinal:plan.ordinal,remoteKey:key})).toBe(true);}expect(await store.beginAttachment(lease)).toBe("STARTED");for(const plan of plans)expect(await store.adoptAttachedPlan(lease,plan.ordinal,`fictional/${plan.ordinal}`)).toBe(true);await pool.query("UPDATE partner_jobs SET final_quote_number='WRONG' WHERE company_id=$1 AND id=$2",[companyId,jobId]);expect(await store.finalizeSubmission(lease,plans.length)).toBe(false);await pool.query("UPDATE partner_jobs SET final_quote_number='NW-1' WHERE company_id=$1 AND id=$2",[companyId,jobId]);await pool.query("UPDATE partner_site_plan_drawings SET submitted_pdf_storage_key='foreign/key' WHERE company_id=$1 AND job_id=$2 AND id=$3",[companyId,jobId,plans[0].drawingId]);expect(await store.finalizeSubmission(lease,plans.length)).toBe(false);await pool.query("UPDATE partner_site_plan_drawings SET submitted_pdf_storage_key=$4,submitted_snapshot_data=$5::jsonb WHERE company_id=$1 AND job_id=$2 AND id=$3",[companyId,jobId,plans[0].drawingId,"fictional/0",JSON.stringify(EMPTY_SITE_PLAN_DOCUMENT)]);expect(await store.finalizeSubmission(lease,plans.length)).toBe(false);await pool.query("UPDATE partner_site_plan_drawings SET submitted_snapshot_data=drawing_data WHERE company_id=$1 AND job_id=$2 AND id=$3",[companyId,jobId,plans[0].drawingId]);await pool.query("UPDATE partner_site_plan_pdf_artifacts SET render_hash=$4 WHERE company_id=$1 AND job_id=$2 AND id=$3",[companyId,jobId,plans[0].artifactId,"c".repeat(64)]);expect(await store.finalizeSubmission(lease,plans.length)).toBe(false);expect((await pool.query("SELECT submission_state FROM partner_jobs WHERE id=$1",[jobId])).rows[0].submission_state).toBe("ATTACHING_PLANS");expect((await pool.query("SELECT id FROM partner_outbox_events WHERE request_id=$1 AND topic='PARTNER_SUBMISSION_COMPLETED'",[workerScope.requestId])).rowCount).toBe(0);});
  it("atomically restores and poisons a late finalize fault until reset",async()=>{const{pool,workerScope}=await acceptedFixture();let injected=false;const faultSql={query:async(text:string,values?:readonly unknown[])=>{if(!injected&&text.includes("INSERT INTO partner_outbox_events")&&text.includes("notification_phase")){injected=true;throw new Error("injected notification insert fault");}return pool.query(text,[...(values??[])]);}} as PartnerSql;const engine=new PartnerSubmissionWorkerEngine(createPartnerDemoSubmissionWorkerRepository(faultSql,workerScope,env()),{env:env(),leaseSeconds:120,deadlineMs:45_000,resolveNotificationAdapter:()=>createFictionalNotificationAdapterTestHarness()});await engine.runOnce("faulting-worker");const state=await pool.query<{submission_state:string;submission_checkpoint:string}>("SELECT submission_state,submission_checkpoint FROM partner_jobs WHERE company_id=$1 AND id=$2",[companyId,jobId]),events=await pool.query("SELECT id FROM partner_outbox_events WHERE company_id=$1 AND job_id=$2 AND topic='PARTNER_SUBMISSION_COMPLETED'",[companyId,jobId]);expect(injected).toBe(true);expect(state.rows[0]).toEqual({submission_state:"ATTACHING_PLANS",submission_checkpoint:"PLANS_ATTACHED"});expect(events.rowCount).toBe(0);expect(partnerDemoSubmissionPoisoned(companyId,jobId)).toBe(true);expect(()=>signalPartnerDemoSubmissionWorker(scope,env())).toThrow("PARTNER_DEMO_RESET_REQUIRED");await resetPartnerDemoSubmissionRuntime(env());expect((await getPartnerDemoPool().query("SELECT submission_state FROM partner_jobs WHERE id=$1",[jobId])).rows[0].submission_state).toBe("DRAFT");});
  it("serializes reset against a running drain and rejects overlapping signals",async()=>{await acceptedFixture();const running=signalPartnerDemoSubmissionWorker(scope,env()),resetting=resetPartnerDemoSubmissionRuntime(env());expect(()=>signalPartnerDemoSubmissionWorker(scope,env())).toThrow("PARTNER_DEMO_RESET_IN_PROGRESS");await Promise.allSettled([running,resetting]);expect(partnerDemoWorkerState()).toMatchObject({state:"IDLE",resetting:false,signals:0,runs:0});expect((await getPartnerDemoPool().query("SELECT submission_state FROM partner_jobs WHERE id=$1",[jobId])).rows[0].submission_state).toBe("DRAFT");});
});
