import { afterEach, describe, expect, it, vi } from "vitest";
import { EMPTY_SITE_PLAN_DOCUMENT } from "../site-plan-drawings";
import { createPartnerTestDatabase } from "./test-db";
import { PartnerSitePlanRepository } from "./site-plan-repository";
import type { PartnerPrincipal } from "./repository";
import { createHash } from "node:crypto";

const pools: Array<{end():Promise<void>}> = [];
afterEach(async()=>{await Promise.all(pools.splice(0).map((pool)=>pool.end()));vi.unstubAllEnvs();});
async function fixture(){const{Pool}=createPartnerTestDatabase();const pool=new Pool();pools.push(pool);const companyId=(await pool.query("INSERT INTO partner_companies(slug,name,billing_model)VALUES('plans','Plans','INSULHUB_BILLED') RETURNING id")).rows[0].id;await pool.query("INSERT INTO partner_users(id,company_id,principal_type,name,email)VALUES('plans-user',$1,'PARTNER','User','plans@test')",[companyId]);const jobId=(await pool.query("INSERT INTO partner_jobs(company_id,created_by_user_id,client_reference,billing_model_snapshot)VALUES($1,'plans-user','plans-job','INSULHUB_BILLED') RETURNING id",[companyId])).rows[0].id;const principal:PartnerPrincipal={userId:"plans-user",companyId,principalType:"PARTNER"};return{pool,jobId,principal,repository:new PartnerSitePlanRepository(pool)};}

describe("partner floor-plan repository",()=>{
  it("uses the narrow company-lock definer for real runtime mutations",async()=>{
    vi.stubEnv("NODE_ENV","production");
    const query=vi.fn(async(text:string)=>{if(text.includes("partner_lock_site_plan_company"))return{rows:[{locked:false}],rowCount:1};if(text==="BEGIN"||text==="COMMIT")return{rows:[],rowCount:null};throw new Error(`Unexpected query: ${text}`);});
    const pool={connect:vi.fn(async()=>({query,release:vi.fn()}))};
    const repository=new PartnerSitePlanRepository(pool as never),principal:PartnerPrincipal={userId:"runtime-user",companyId:"11111111-1111-4111-8111-111111111111",principalType:"PARTNER"};
    await expect(repository.create(principal,"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",0,"Ground",EMPTY_SITE_PLAN_DOCUMENT)).resolves.toEqual({outcome:"not_found"});
    expect(query).toHaveBeenCalledWith("SELECT public.partner_lock_site_plan_company($1) AS locked",[principal.companyId]);
    expect(query.mock.calls.some(([text])=>String(text).includes("FROM partner_companies")&&String(text).includes("FOR UPDATE"))).toBe(false);
  });
  it("invalidates unchanged draft saves, replaces completion, and invalidates every floor after an address change",async()=>{
    const {pool,repository,principal,jobId}=await fixture();
    const document={...EMPTY_SITE_PLAN_DOCUMENT,walls:[{id:"wall",start:{x:1,y:1},end:{x:4,y:1},style:"solid" as const}]};
    await repository.create(principal,jobId,0,"Ground",document); await repository.create(principal,jobId,1,"Upper",document);
    const floors=(await repository.list(principal,jobId))!.floors;
    const bytes=Buffer.from("%PDF-test-completion"),contentSha256=createHash("sha256").update(bytes).digest("hex");
    for(const floor of floors) await repository.publish(principal,jobId,floor.id,(await repository.renderSnapshot(principal,jobId,floor.id))!,{bytes,contentSha256},`${floor.name}.pdf`);
    const first=(await repository.get(principal,jobId,floors[0].id))!;
    expect(first.pdfReady).toBe(true);
    await repository.patch(principal,jobId,first.id,0,{name:first.name,document:first.document});
    const draft=(await repository.get(principal,jobId,first.id))!;expect(draft.pdfReady).toBe(false);expect(draft.currentPdf?.artifactId).toBe(first.currentPdf?.artifactId);
    const completed=await repository.publish(principal,jobId,first.id,(await repository.renderSnapshot(principal,jobId,first.id))!,{bytes,contentSha256},"Ground.pdf");
    expect(completed?.pdfReady).toBe(true); expect(completed?.currentPdf?.artifactId).not.toBe(first.currentPdf?.artifactId);
    await pool.query("UPDATE partner_jobs SET customer_name='Changed contact' WHERE id=$1",[jobId]);
    expect((await repository.list(principal,jobId))!.floors.every(floor=>floor.pdfReady)).toBe(true);
    await pool.query("UPDATE partner_jobs SET site_address=$2::jsonb WHERE id=$1",[jobId,JSON.stringify({street:"New property",city:"Auckland",suburb:"Central",postcode:"1010"})]);
    expect((await repository.list(principal,jobId))!.floors.every(floor=>!floor.pdfReady)).toBe(true);
  });
  it("serializes create, patch, reorder and delete with collection/drawing CAS",async()=>{const{repository,principal,jobId}=await fixture();const created=await repository.create(principal,jobId,0,"Ground",EMPTY_SITE_PLAN_DOCUMENT);expect(created).toMatchObject({outcome:"updated",collection:{revision:1,floors:[{name:"Ground",sortOrder:0}]}});if(created.outcome!=="updated")return;const id=created.collection.floors[0].id;expect(await repository.create(principal,jobId,0,"Stale",EMPTY_SITE_PLAN_DOCUMENT)).toEqual({outcome:"stale",currentRevision:1});const patched=await repository.patch(principal,jobId,id,0,{name:"Ground floor"});expect(patched).toMatchObject({outcome:"updated",floor:{revision:1,name:"Ground floor"}});expect(await repository.patch(principal,jobId,id,0,{name:"Old"})).toEqual({outcome:"stale",currentRevision:1});const reordered=await repository.reorder(principal,jobId,1,[id]);expect(reordered).toMatchObject({outcome:"updated",collection:{revision:2}});expect(await repository.remove(principal,jobId,id,2)).toMatchObject({outcome:"updated",collection:{revision:3,floors:[]}});});
  it("keeps same-company paths generic and blocks non-draft writes",async()=>{const{pool,repository,principal,jobId}=await fixture();await pool.query("UPDATE partner_jobs SET submission_state='QUEUED',submission_started_at=now() WHERE id=$1",[jobId]);expect(await repository.create(principal,jobId,0,"Ground",EMPTY_SITE_PLAN_DOCUMENT)).toEqual({outcome:"not_draft"});expect(await repository.get({...principal,companyId:"22222222-2222-4222-8222-222222222222"},jobId,"dddddddd-dddd-4ddd-8ddd-dddddddddddd")).toBeNull();});
  it("publishes revision-current verified artifacts and handles edit to revert",async()=>{const{repository,principal,jobId}=await fixture();const wall={id:"wall-1",start:{x:1,y:1},end:{x:6,y:1},style:"solid" as const};const created=await repository.create(principal,jobId,0,"Ground",{...EMPTY_SITE_PLAN_DOCUMENT,walls:[wall]});if(created.outcome!=="updated")throw new Error("create failed");const id=created.collection.floors[0].id;const pdf=Buffer.from("%PDF-1.7\nfixture");const contentSha256=createHash("sha256").update(pdf).digest("hex");const firstSnapshot=await repository.renderSnapshot(principal,jobId,id);expect(firstSnapshot).not.toBeNull();const first=await repository.publish(principal,jobId,id,firstSnapshot!,{bytes:pdf,contentSha256},"Ground.pdf");expect(first).toMatchObject({pdfReady:true,currentPdf:{drawingRevision:0}});const againSnapshot=await repository.renderSnapshot(principal,jobId,id);expect(await repository.publish(principal,jobId,id,againSnapshot!,{bytes:pdf,contentSha256},"Ground.pdf")).toMatchObject({pdfReady:true,currentPdf:{artifactId:first!.currentPdf!.artifactId}});await repository.patch(principal,jobId,id,0,{document:EMPTY_SITE_PLAN_DOCUMENT});await repository.patch(principal,jobId,id,1,{document:{...EMPTY_SITE_PLAN_DOCUMENT,walls:[wall]}});const revertedSnapshot=await repository.renderSnapshot(principal,jobId,id);const reverted=await repository.publish(principal,jobId,id,revertedSnapshot!,{bytes:pdf,contentSha256},"Ground.pdf");expect(reverted).toMatchObject({pdfReady:true,currentPdf:{drawingRevision:2}});expect(reverted!.currentPdf!.artifactId).not.toBe(first!.currentPdf!.artifactId);});
  it("rejects an address race at publication without creating an artifact",async()=>{const{pool,repository,principal,jobId}=await fixture();const document={...EMPTY_SITE_PLAN_DOCUMENT,walls:[{id:"wall-1",start:{x:1,y:1},end:{x:2,y:2},style:"solid" as const}]};const created=await repository.create(principal,jobId,0,"Ground",document);if(created.outcome!=="updated")throw new Error("create failed");const id=created.collection.floors[0].id;const snapshot=await repository.renderSnapshot(principal,jobId,id);await pool.query("UPDATE partner_jobs SET site_address=$2::jsonb WHERE id=$1",[jobId,JSON.stringify({street:"Changed after render"})]);const bytes=Buffer.from("%PDF-race");const contentSha256=createHash("sha256").update(bytes).digest("hex");expect(await repository.publish(principal,jobId,id,snapshot!,{bytes,contentSha256},"Ground.pdf")).toBeNull();expect((await pool.query("SELECT 1 FROM partner_site_plan_pdf_artifacts WHERE drawing_id=$1",[id])).rowCount).toBe(0);});
  it("recomputes current download bytes and fails closed on corruption",async()=>{const{pool,repository,principal,jobId}=await fixture();const document={...EMPTY_SITE_PLAN_DOCUMENT,walls:[{id:"wall-1",start:{x:1,y:1},end:{x:2,y:2},style:"solid" as const}]};const created=await repository.create(principal,jobId,0,"Ground",document);if(created.outcome!=="updated")throw new Error("create failed");const id=created.collection.floors[0].id;const snapshot=await repository.renderSnapshot(principal,jobId,id);const bytes=Buffer.from("%PDF-valid");const contentSha256=createHash("sha256").update(bytes).digest("hex");await repository.publish(principal,jobId,id,snapshot!,{bytes,contentSha256},"Ground.pdf");const corrupted=Buffer.from("%PDF-corrupt");await pool.query("UPDATE partner_site_plan_pdf_artifacts SET pdf_bytes=$2,byte_size=$3 WHERE drawing_id=$1",[id,corrupted,corrupted.byteLength]);await expect(repository.download(principal,jobId,id)).rejects.toThrow("verification failed");});
  it("atomically purges, compacts and increments exactly once through the empty branch",async()=>{const{pool,repository,principal,jobId}=await fixture();const ground=await repository.create(principal,jobId,0,"Ground",EMPTY_SITE_PLAN_DOCUMENT);const upper=await repository.create(principal,jobId,1,"Upper",EMPTY_SITE_PLAN_DOCUMENT);const loft=await repository.create(principal,jobId,2,"Loft",EMPTY_SITE_PLAN_DOCUMENT);if(ground.outcome!=="updated"||upper.outcome!=="updated"||loft.outcome!=="updated")throw new Error("create failed");const upperId=upper.collection.floors.find((floor)=>floor.name==="Upper")!.id;const middle=await repository.remove(principal,jobId,upperId,3);expect(middle).toMatchObject({outcome:"updated",collection:{revision:4,floors:[{name:"Ground",sortOrder:0},{name:"Loft",sortOrder:1}]}});if(middle.outcome!=="updated")return;const groundId=middle.collection.floors[0].id;const afterGround=await repository.remove(principal,jobId,groundId,4);expect(afterGround).toMatchObject({outcome:"updated",collection:{revision:5,floors:[{name:"Loft",sortOrder:0}]}});if(afterGround.outcome!=="updated")return;expect(await repository.remove(principal,jobId,afterGround.collection.floors[0].id,5)).toMatchObject({outcome:"updated",collection:{revision:6,floors:[]}});expect((await pool.query("SELECT floor_plan_revision FROM partner_jobs WHERE id=$1",[jobId])).rows[0].floor_plan_revision).toBe(6);});
  it("serializes concurrent first-hit generation and download limits atomically",async()=>{const{repository}=await fixture();const generate=await Promise.all(Array.from({length:12},()=>repository.consumeRateLimit("user:concurrent-generate","GENERATE",600,10)));expect(generate.filter(Boolean)).toHaveLength(10);const download=await Promise.all(Array.from({length:122},()=>repository.consumeRateLimit("user:concurrent-download","DOWNLOAD",600,120)));expect(download.filter(Boolean)).toHaveLength(120);});
});
