import "server-only";
import { NextResponse } from "next/server";
import { getAuthenticatedPrincipal } from "./auth";
import { getPartnerPool } from "./db";
import type { AuthenticatedPrincipal, PartnerPrincipal } from "./repository";
import { allowedPartnerOrigins, verifyMutationOrigin, verifyPartnerRequestHost, withPartnerNoStore } from "./security";
import { isUuid, parseSitePlanDocument } from "../site-plan-drawings";
import { PartnerSitePlanRepository, normalizeFloorPlanName, type FloorPlanCollection, type PartnerFloorPlan } from "./site-plan-repository";
import { renderPartnerSitePlanPdf } from "./site-plan-renderer";

const MAX_BODY = 256 * 1024;
type Dependencies = { repository: PartnerSitePlanRepository; origins: ReadonlySet<string>; getPrincipal(headers:Headers):Promise<AuthenticatedPrincipal|null>; render:typeof renderPartnerSitePlanPdf };
function deps():Dependencies{return{repository:new PartnerSitePlanRepository(getPartnerPool()),origins:allowedPartnerOrigins(),getPrincipal:getAuthenticatedPrincipal,render:renderPartnerSitePlanPdf};}
function json(body:unknown,init?:ResponseInit){return withPartnerNoStore(NextResponse.json(body,init));}
function partner(principal:AuthenticatedPrincipal|null):PartnerPrincipal|null{return principal?.principalType==="PARTNER"?principal:null;}
function invalidHost(injected:Dependencies|undefined,headers:Headers){return!injected&&!verifyPartnerRequestHost(headers);}
function notFound(){return json({error:"Floor plan not found."},{status:404});}
function session(){return json({error:"Your session has expired. Sign in again."},{status:401});}
function validRevision(value:unknown):value is number{return Number.isInteger(value)&&Number(value)>=0&&Number(value)<=2_147_483_647;}
function exact(value:unknown,keys:readonly string[]):value is Record<string,unknown>{return!!value&&typeof value==="object"&&!Array.isArray(value)&&Object.keys(value).every((key)=>keys.includes(key))&&keys.every((key)=>Object.hasOwn(value,key));}
async function body(request:Request):Promise<unknown>{const length=Number(request.headers.get("content-length")??0);if(length>MAX_BODY)throw new Error("BODY_TOO_LARGE");const text=await request.text();if(new TextEncoder().encode(text).byteLength>MAX_BODY)throw new Error("BODY_TOO_LARGE");try{return JSON.parse(text);}catch{return null;}}
async function context(request:Request,injected?:Dependencies):Promise<{d:Dependencies;p:PartnerPrincipal}|NextResponse>{if(invalidHost(injected,request.headers))return json({error:"Forbidden"},{status:403});const d=injected??deps();const p=partner(await d.getPrincipal(request.headers));return p?{d,p}:session();}
function mutationFailure(request:Request,d:Dependencies){return verifyMutationOrigin(request.headers,d.origins)?null:json({error:"Forbidden"},{status:403});}
function publicFloor(floor:PartnerFloorPlan){return{...floor,currentPdf:floor.currentPdf?{drawingRevision:floor.currentPdf.drawingRevision,fileName:floor.currentPdf.fileName,generatedAt:floor.currentPdf.generatedAt}:null};}
function publicCollection(collection:FloorPlanCollection){return{revision:collection.revision,floors:collection.floors.map(publicFloor)};}
function mutationResult(result:Awaited<ReturnType<PartnerSitePlanRepository["create"]>>){if(result.outcome==="updated")return json({floorPlans:publicCollection(result.collection)});if(result.outcome==="not_found")return notFound();if(result.outcome==="not_draft")return json({error:"Submitted jobs cannot be edited.",code:"DRAFT_LOCKED"},{status:409});return json({error:"Floor plans changed in another tab. Reload before saving.",code:"STALE_REVISION",currentRevision:result.currentRevision},{status:409});}
function safeError(error:unknown){if(error instanceof Error&&error.message==="BODY_TOO_LARGE")return json({error:"Request body is too large."},{status:413});if(error instanceof Error&&/unique|duplicate/i.test(error.message))return json({error:"Each floor plan needs a unique name."},{status:409});const failure=error&&typeof error==="object"?error as {name?:unknown;code?:unknown}:null;console.error("[partner:floor-plans] request failed",{name:typeof failure?.name==="string"?failure.name:"Error",code:typeof failure?.code==="string"?failure.code:"UNKNOWN"});return json({error:"The floor plan request could not be completed."},{status:500});}

export async function listFloorPlans(request:Request,jobId:string,injected?:Dependencies){const c=await context(request,injected);if(c instanceof NextResponse)return c;if(!isUuid(jobId))return notFound();const collection=await c.d.repository.list(c.p,jobId);return collection?json({floorPlans:publicCollection(collection)}):notFound();}
export async function createFloorPlan(request:Request,jobId:string,injected?:Dependencies){const c=await context(request,injected);if(c instanceof NextResponse)return c;const origin=mutationFailure(request,c.d);if(origin)return origin;if(!isUuid(jobId))return notFound();try{const input=await body(request);if(!exact(input,["revision","name","document"])||!validRevision(input.revision))return json({error:"Floor plan input is invalid."},{status:400});const name=normalizeFloorPlanName(input.name);const document=parseSitePlanDocument(input.document);if(!name||!document)return json({error:"Floor plan input is invalid."},{status:400});return mutationResult(await c.d.repository.create(c.p,jobId,input.revision,name,document));}catch(error){return safeError(error);}}
export async function getFloorPlan(request:Request,jobId:string,drawingId:string,injected?:Dependencies){const c=await context(request,injected);if(c instanceof NextResponse)return c;if(!isUuid(jobId)||!isUuid(drawingId))return notFound();const floor=await c.d.repository.get(c.p,jobId,drawingId);return floor?json({floorPlan:publicFloor(floor)}):notFound();}
export async function patchFloorPlan(request:Request,jobId:string,drawingId:string,injected?:Dependencies){const c=await context(request,injected);if(c instanceof NextResponse)return c;const origin=mutationFailure(request,c.d);if(origin)return origin;if(!isUuid(jobId)||!isUuid(drawingId))return notFound();try{const input=await body(request);if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).some((key)=>!["revision","name","document"].includes(key))||!Object.hasOwn(input,"revision")||!validRevision((input as Record<string,unknown>).revision))return json({error:"Floor plan update is invalid."},{status:400});const record=input as Record<string,unknown>;const update:{name?:string;document?:ReturnType<typeof parseSitePlanDocument>}={};if("name"in record){const name=normalizeFloorPlanName(record.name);if(!name)return json({error:"Floor plan update is invalid."},{status:400});update.name=name;}if("document"in record){const document=parseSitePlanDocument(record.document);if(!document)return json({error:"Floor plan update is invalid."},{status:400});update.document=document;}if(!update.name&&!update.document)return json({error:"Floor plan update is invalid."},{status:400});const result=await c.d.repository.patch(c.p,jobId,drawingId,record.revision as number,update as {name?:string;document?:NonNullable<ReturnType<typeof parseSitePlanDocument>>});if(result.outcome==="updated")return json({floorPlan:publicFloor(result.floor)});if(result.outcome==="not_found")return notFound();if(result.outcome==="not_draft")return json({error:"Submitted jobs cannot be edited.",code:"DRAFT_LOCKED"},{status:409});return json({error:"This floor plan changed in another tab. Reload before saving.",code:"STALE_REVISION",currentRevision:result.currentRevision},{status:409});}catch(error){return safeError(error);}}
export async function deleteFloorPlan(request:Request,jobId:string,drawingId:string,injected?:Dependencies){const c=await context(request,injected);if(c instanceof NextResponse)return c;const origin=mutationFailure(request,c.d);if(origin)return origin;if(!isUuid(jobId)||!isUuid(drawingId))return notFound();try{const input=await body(request);if(!exact(input,["revision"])||!validRevision(input.revision))return json({error:"Floor plan delete is invalid."},{status:400});return mutationResult(await c.d.repository.remove(c.p,jobId,drawingId,input.revision));}catch(error){return safeError(error);}}
export async function reorderFloorPlans(request:Request,jobId:string,injected?:Dependencies){const c=await context(request,injected);if(c instanceof NextResponse)return c;const origin=mutationFailure(request,c.d);if(origin)return origin;if(!isUuid(jobId))return notFound();try{const input=await body(request);if(!exact(input,["revision","drawingIds"])||!validRevision(input.revision)||!Array.isArray(input.drawingIds)||input.drawingIds.length>20||input.drawingIds.some((id)=>typeof id!=="string"||!isUuid(id)))return json({error:"Floor plan order is invalid."},{status:400});return mutationResult(await c.d.repository.reorder(c.p,jobId,input.revision,input.drawingIds as string[]));}catch(error){return safeError(error);}}
function scalarText(value:string){return [...value].map((character)=>{const code=character.codePointAt(0)!;return code>=0xd800&&code<=0xdfff?"_":character;}).join("");}
function truncateCodePoints(value:string,maximum:number){return[...value].slice(0,maximum).join("");}
function filename(value:string){let cleaned=scalarText(value).normalize("NFC").replace(/[\r\n"\\/;\u0000-\u001f\u007f-\u009f]/g,"-").replace(/\s+/g," ").trim().replace(/\.pdf$/iu,"").trim();if(!cleaned||/^\.+$/.test(cleaned))cleaned="site-plan";cleaned=truncateCodePoints(cleaned,176).replace(/[. ]+$/g,"")||"site-plan";return`${cleaned}.pdf`;}
function disposition(value:string){const utf8=filename(value);const asciiStem=truncateCodePoints([...utf8.replace(/\.pdf$/iu,"").normalize("NFKD")].map((character)=>{const code=character.codePointAt(0)!;return code>=0x20&&code<=0x7e&&!/["\\]/.test(character)?character:"_";}).join(""),176).replace(/[. ]+$/g,"")||"site-plan";const ascii=`${asciiStem}.pdf`;const encoded=encodeURIComponent(utf8).replace(/[!'()*]/g,(character)=>`%${character.charCodeAt(0).toString(16).toUpperCase()}`);return `attachment; filename="${ascii}"; filename*=UTF-8''${encoded}`;}
export async function generateFloorPlanPdf(request: Request, jobId: string, drawingId: string, injected?: Dependencies) {
  const c = await context(request, injected); if (c instanceof NextResponse) return c;
  const origin = mutationFailure(request, c.d); if (origin) return origin;
  if (!isUuid(jobId) || !isUuid(drawingId)) return notFound();
  let input: unknown;
  try { input = await body(request); } catch (error) { return safeError(error); }
  if (!exact(input, ["revision"]) || !validRevision(input.revision)) return json({ error: "The saved drawing version is required." }, { status: 400 });
  let withinLimit: boolean;
  try {
    const [userAllowed, companyAllowed] = await Promise.all([
      c.d.repository.consumeRateLimit(`user:${c.p.userId}`, "GENERATE", 600, 10),
      c.d.repository.consumeRateLimit(`company:${c.p.companyId}`, "GENERATE", 3600, 30),
    ]);
    withinLimit = userAllowed && companyAllowed;
  } catch { return json({ error: "Floor completion could not be started. Try again later." }, { status: 503 }); }
  if (!withinLimit) return json({ error: "Floor completion limit reached. Try again later." }, { status: 429 });
  const snapshot = await c.d.repository.renderSnapshot(c.p, jobId, drawingId); if (!snapshot) return notFound();
  if (snapshot.drawingRevision !== input.revision) return json({ error: "This floor changed in another tab. Reload before marking it complete.", code: "STALE_REVISION" }, { status: 409 });
  if (snapshot.input.document.walls.length === 0) return json({ error: "Draw at least one wall before marking the floor complete." }, { status: 400 });
  try {
    const rendered = await c.d.render(snapshot.input);
    const floor = await c.d.repository.publish(c.p, jobId, drawingId, snapshot, rendered, filename(snapshot.input.drawingName));
    return floor ? json({ floorPlan: publicFloor(floor) }, { status: 201 }) : json({ error: "The draft changed while completing this floor. Reload and try again.", code: "STALE_REVISION" }, { status: 409 });
  } catch { return json({ error: "The floor could not be completed. Your saved drawing remains a draft; try again." }, { status: 422 }); }
}
export async function downloadFloorPlanPdf(request:Request,jobId:string,drawingId:string,injected?:Dependencies){const c=await context(request,injected);if(c instanceof NextResponse)return c;if(!isUuid(jobId)||!isUuid(drawingId))return notFound();let withinLimit:boolean;try{withinLimit=await c.d.repository.consumeRateLimit(`user:${c.p.userId}`,"DOWNLOAD",600,120);}catch{return json({error:"The download could not be started. Try again later."},{status:503});}if(!withinLimit)return json({error:"Download limit reached. Try again later."},{status:429});try{const artifact=await c.d.repository.download(c.p,jobId,drawingId);if(!artifact)return notFound();return withPartnerNoStore(new NextResponse(new Uint8Array(artifact.bytes),{status:200,headers:{"content-type":"application/pdf","content-length":String(artifact.bytes.byteLength),"content-disposition":disposition(artifact.fileName),"x-content-type-options":"nosniff","content-security-policy":"default-src 'none'; sandbox","cross-origin-resource-policy":"same-origin","x-site-plan-content-sha256":artifact.sha256}}));}catch{return json({error:"The stored PDF could not be verified."},{status:422});}}
export type { Dependencies as PartnerSitePlanRouteDependencies };
